package com.oleksandrkarpiuk.recipemaster.utils

object SpoonacularTags {
    
    const val DIETS = "diets"
    const val CUISINES = "cuisines"
    const val MEAL_TYPES = "mealTypes"

    const val DAIRY_FREE = "dairy free"
    const val GLUTEN_FREE = "gluten free"
    const val KETOGENIC = "ketogenic"
    const val LACTO_OVO_VEGETARIAN = "lacto ovo vegetarian"
    const val PALEOLITHIC = "paleolithic"
    const val PESCATARIAN = "pescatarian"
    const val PRIMAL = "primal"
    const val VEGAN = "vegan"
    const val VEGETARIAN = "vegetarian"
    
    const val AMERICAN = "american"
    const val ASIAN = "asian"
    const val BRITISH = "british"
    const val CAJUN = "cajun"
    const val CHINESE = "chinese"
    const val EUROPEAN = "european"
    const val FRENCH = "french"
    const val INDIAN = "indian"
    const val IRISH = "irish"
    const val ITALIAN = "italian"
    const val MEDITERRANEAN = "mediterranean"
    const val SOUTHERN = "southern"
    
    const val BREAKFAST = "breakfast"
    const val BRUNCH = "brunch"
    const val LUNCH = "lunch"
    const val DINNER = "dinner"
    const val ANTIPASTI = "antipasti"
    const val APPETIZER = "appetizer"
    const val BREAD = "bread"
    const val DESSERT = "dessert"
    const val DRINK = "drink"
    const val MAIN_COURSE = "main course"
    const val MAIN_DISH = "main dish"
    const val SALAD = "salad"
    const val SAUCE = "sauce"
    const val SIDE_DISH = "side dish"
    const val SNACK = "snack"
    const val SOUP = "soup"
    const val STARTER = "starter"
    
}